name: bcms_app
description: A mobile app for music students
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  #sdk: ">=2.7.1 <3.0.0"
  sdk: ">=2.3.0 <3.0.0"
  #sdk: ">=2.0.0-dev.68.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #for ADMIN PIN
  #pin_code_text_field:
  pinput: ^0.2.0

  #to view PDFs
  #flutter_full_pdf_viewer: ^1.0.4
  #flutter_full_pdf_viewer: ^1.0.6
  #flutter_plugin_pdf_viewer: ^1.0.7
  native_pdf_view: any
  flutter_pdfview:
  pdftron_flutter:
    git:
      url: git://github.com/PDFTron/pdftron-flutter.git
  #permission_handler: '3.0.1'

#homework
  #I don't see myself using this:
  google_sign_in: ^4.0.1+3


#for the registration function
  flutter_form_builder: ^3.13.3

#for fire store
  #firebase_auth: ^0.16.0
  firebase_auth: ^0.16.1
  #cloud_firestore: ^0.13.5
  cloud_firestore: ^0.13.7
  #provider: ^4.0.5
  provider: ^4.3.1
  flutter_spinkit: ^4.1.2+1
  #intl: ^0.16.0
  intl: any
  #share: ^0.6.4
  share: ^0.6.4+3

#for the to-do list
  datetime_picker_formfield: ^1.0.0
  #sqflite: any
  sqflite: ^1.1.7+2
  path_provider: any
  flutter_localizations:
    sdk: flutter
  #shared_preferences: ^0.5.7
  shared_preferences: ^0.5.8

#for the calendar
  table_calendar: ^2.2.3
  #gradient_app_bar: ^0.0.1
  gradient_app_bar: ^0.1.3
  beautifulsoup: ^0.0.1
  #retry: ^3.0.0+1
  retry: ^3.0.1
  #url_launcher: ^5.1.3
  url_launcher: ^5.5.0
  #percent_indicator: ^2.1.1+1
  percent_indicator: ^2.1.6
  #simple_animations: ^1.3.11
  #sinple_animations: ^2.2.1
  #onesignal_flutter: ^2.0.0
  #onesignal_flutter: ^2.6.0
  #for the browser ability
  http:

  mockito: 4.1.1
  json_annotation: ^3.0.0
  english_words: ^3.1.0
  #havin issues with these
  #flutter_sms: ^2.0.0+2
  #firebase_in_app_messaging: ^0.1.1+3
  cupertino_icons: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  #I'll try the icons for later
  flutter_launcher_icons: ^0.7.5
  json_serializable: ^3.0.0
  build_runner: ^1.10.0
#For if/when I make an icon for this app:
flutter_icons:
  #image_path: "assets/icon.png"
  android: true
  #ios: true

# The following section is specific to Flutter.
flutter:

  # Material Icons font
  uses-material-design: true

  # assets:
  assets:
    - assets/
